spring.application.name=springboard

#oracle
spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/FREEPDB1
spring.datasource.username=tokyo
spring.datasource.password=001020
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

#jpa
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

#log
logging.level.org.hibernate.SQL = DEBUG
logging.level.org.hibernate.type.descriptor.sql = trace

# ?? ??? 10MB
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
# ?? ??? ???? ? ?
file.upload-dir=uploads

# security
# JWT secret key (72byte ?? ??) - ?? ? ??
# JWT json web token
#[https://generate-secret.vercel.app/](https://generate-secret.vercel.app/)
jwt.secret=ThisIsMyProject**4c289b803fa99e3c31f62b888c63fcd3@board
# jwt ????: 1??(ms)
jwt.expiration=3600000

server.port=8081

# data.sql
#spring.sql.init.mode=always
spring.sql.init.data-locations=classpath:data.sql
spring.sql.init.encoding=UTF-8
spring.jpa.defer-datasource-initialization=true